In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import OneHotEncoder

In [ ]:
train_df = pd.read_csv("rossmann-store-sales/train.csv")
train_df

C:\Users\zand\AppData\Local\Temp\ipykernel_9364\3133258850.py:1: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  train_df = pd.read_csv("rossmann-store-sales/train.csv")

,Store,DayOfWeek,Date,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday
0,1,5,2015-07-31,5263,555,1,1,0,1
1,2,5,2015-07-31,6064,625,1,1,0,1
2,3,5,2015-07-31,8314,821,1,1,0,1
3,4,5,2015-07-31,13995,1498,1,1,0,1
4,5,5,2015-07-31,4822,559,1,1,0,1
...,...,...,...,...,...,...,...,...,...
1017204,1111,2,2013-01-01,0,0,0,0,a,1
1017205,1112,2,2013-01-01,0,0,0,0,a,1
1017206,1113,2,2013-01-01,0,0,0,0,a,1
1017207,1114,2,2013-01-01,0,0,0,0,a,1
1017208,1115,2,2013-01-01,0,0,0,0,a,1

In [ ]:
train_df.shape

In [ ]:
train_df.info()

In [ ]:
train_df.describe()

In [ ]:
train_df.columns.tolist()

In [ ]:
train_df.duplicated().sum()

In [ ]:
train_df.isnull().sum()

In [ ]:
train_df['Date'] = pd.to_datetime(train_df["Date"])
train_df.dtypes

Store                     int64
DayOfWeek                 int64
Date             datetime64[ns]
Sales                     int64
Customers                 int64
Open                      int64
Promo                     int64
StateHoliday             object
SchoolHoliday             int64
dtype: object

In [ ]:
train_df['year'] = train_df['Date'].dt.year 
train_df['month'] = train_df['Date'].dt.month
train_df['day'] = train_df['Date'].dt.day
train_df['week'] = train_df['Date'].dt.isocalendar().week.astype(int)
train_df.drop(columns= 'Date', inplace=True)
train_df.head()

,Store,DayOfWeek,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday,year,month,day,week
0,1,5,5263,555,1,1,0,1,2015,7,31,31
1,2,5,6064,625,1,1,0,1,2015,7,31,31
2,3,5,8314,821,1,1,0,1,2015,7,31,31
3,4,5,13995,1498,1,1,0,1,2015,7,31,31
4,5,5,4822,559,1,1,0,1,2015,7,31,31

In [ ]:
train_df.dtypes

In [ ]:
target = ["Sales"]
num_cols = ['Customers', 'day', 'month', 'year', 'week']
cat_cols = ['Store', 'DayOfWeek', 'Open', 'Promo', 'StateHoliday', 'SchoolHoliday']

In [ ]:
train_df[num_cols].describe()

          Customers           day         month          year          week
count  1.017209e+06  1.017209e+06  1.017209e+06  1.017209e+06  1.017209e+06
mean   6.331459e+02  1.570279e+01  5.846762e+00  2.013832e+03  2.361551e+01
std    4.644117e+02  8.787638e+00  3.326097e+00  7.773960e-01  1.443338e+01
min    0.000000e+00  1.000000e+00  1.000000e+00  2.013000e+03  1.000000e+00
25%    4.050000e+02  8.000000e+00  3.000000e+00  2.013000e+03  1.100000e+01
50%    6.090000e+02  1.600000e+01  6.000000e+00  2.014000e+03  2.200000e+01
75%    8.370000e+02  2.300000e+01  8.000000e+00  2.014000e+03  3.500000e+01
max    7.388000e+03  3.100000e+01  1.200000e+01  2.015000e+03  5.200000e+01

univariate analayze

In [ ]:
plt.figure(figsize=(6,4))
plt.hist(train_df[target])
plt.show()

In [ ]:
for col in num_cols :
    plt.figure(figsize=(6,4))
    plt.hist(train_df[col])
    plt.title(col)
    plt.xlabel(col)
    plt.show()

bivariate analyze

In [ ]:
for col in num_cols :
    plt.Figure(figsize=(6,4))
    sns.regplot(data=train_df, x=col, y=target)
    plt.show()

In [ ]:
for col in cat_cols :
    plt.figure(figsize=(6,4))
    sns.boxplot(data=train_df, x=col, y=target)
    plt.show()